//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TFTP.RC
//
#define IDC_PICDRAG                     1000
#define IDC_TRANSFERLIST                1000
#define IDC_SERVERTRANSFERS             1001
#define IDC_BINARY                      1001
#define IDC_COMMAND1                    1002
#define IDC_SERVERSTATUS                1002
#define IDC_COMMAND2                    1003
#define IDC_CLIENTSTATUS                1003
#define IDC_COMMAND3                    1004
#define IDC_TFTP1                       1005
#define IDC_SERVERTEXT                  1006
#define IDC_COMMAND5                    1007
#define IDC_DISABLECLIENT               1007
#define IDC_COMMAND6                    1008
#define IDC_ABORTCLIENT                 1008
#define IDC_TFTP2                       1009
#define IDC_COMMAND7                    1010
#define IDC_PUT                         1010
#define IDC_COMMAND8                    1011
#define IDC_GET                         1011
#define IDC_LOCALFILESPEC               1012
#define IDC_REMOTEFILESPEC              1013
#define IDC_HOSTNAME                    1014
#define IDC_CLIENTTEXT                  1015
#define IDC_CLIENTLOG                   1015
#define IDC_BIN                         1016
#define IDC_COMMAND4                    1017
#define IDC_ENABLECLIENT                1017
#define IDC_COMMAND10                   1018
#define IDC_ABOUT                       1018
#define IDC_IMAGE1                      1019
#define IDC_LINE1                       1020
#define IDC_DISABLESERVER               1021
#define IDC_ABORTSERVER                 1022
#define IDC_ENABLESERVER                1023
#define IDC_SERVERLOG                   1024
#define IDC_SAMPLEUSING                 2001
#define IDC_BIGICON                     2002
#define IDC_DARTLOGO                    2003
#define IDC_PROCESSOR                   2004
#define IDC_MEMORYAVAIL                 2005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
