//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MVTerminal.rc
//
#define IDR_MVTerminalTYPE_CNTR_IP      6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_TFTP_SERVER_PANE            101
#define IDP_FAILED_TO_CREATE            102
#define IDC_POINTER                     104
#define IDD_ODPG_CTRL_DLG               105
#define IDR_HTML_SUB20GPIOCTRLDLG       109
#define IDD_PLATFORMINFOSETTINGSDLG     113
#define IDR_MAINFRAME                   128
#define IDR_MVTerminalTYPE              129
#define IDR_MAINFRAME1                  129
#define IDR_MAINFRAME_NORMAL            129
#define IDR_MAINFRAME_DISABLED          129
#define IDR_PANE_TFTP_SERVER            130
#define IDD_PORT_PROPERTIES_DLG         130
#define IDD_CONNECTION_SETTINGS_DLG     130
#define IDR_PANE_SEND_SCRIPT            131
#define IDD_SEND_SCRIPT_PANE            131
#define ID_INDICATOR_STATUS             132
#define IDD_VIEW_PROPERTIES             132
#define ID_INDICATOR_TIME               133
#define IDD_MONITOR_PARAMS_SETTINGS_DLG 133
#define IDR_PANE_REG_ANALYZER           134
#define IDD_APP_SETTINGS_DLG            134
#define IDR_PANE_DATA_ANALYZER          134
#define IDD_GENERAL_SETTINGS_DLG        135
#define IDD_SCRIPT_SETTINGS_DLG         135
#define ID_HISTORY_CMD                  135
#define IDD_APP_SCRIPT_SETTINGS_DLG     135
#define IDD_DATA_ANALYZER_PANE          136
#define IDB_PANES_BITMAP                136
#define ID_HISTORY_CMD_CLEAR            136
#define IDR_PANE_HARDWARE_MODULES       137
#define IDD_APP_APPEARANCE_SETTINGS_DLG 138
#define IDR_PANE_CMD_EXECUTER           138
#define IDR_MENU_ICONS                  139
#define IDR_PANE_PLATFORM_INFO          139
#define IDC_PROPERTY_GRID               140
#define IDD_CMD_HISTORY_SETTINGS_DLG    143
#define IDD_TFTP_SERVER_SETTINGS_DLG    144
#define IDD_APP_TFTP_SERVER_SETTINGS_DLG 144
#define IDB_MARVELL_LOGO                150
#define IDR_POPUP_TABS                  151
#define IDD_SEND_EMAIL                  152
#define IDR_HISTORY_MENU                154
#define IDD_MAIL_SETTINGS               155
#define IDB_CLOSE                       158
#define IDB_NOTIFICATION_CAPTION        159
#define IDB_NOTIFICATION_LOGO           160
#define IDD_VIEW_MESSAGING              161
#define IDI_ICON2                       163
#define IDD_IP_ADDRESS_LIST_DLG         164
#define IDD_IOCARD_SETTINGS_DLG         167
#define IDD_HW_MODULES_SETTINGS_DLG     167
#define IDD_CE_CHECK_RESULT_DLG         173
#define IDD_CE_EXECUTE_CMD_DLG          174
#define IDD_CMDE_CMD_SETTINGS_DLG       174
#define IDR_CMDE_STATE_MENU             174
#define IDD_CE_CMD_SETTINGS_DLG         174
#define IDD_CMD_EXE_CMD_SETTINGS_DLG    174
#define IDD_CE_SET_DELAY_DLG            175
#define IDD_CE_WAIT_FOR_STR_DLG         176
#define IDR_CMDE_FILE_CMD_MENU          176
#define IDR_CMDE_INSERT_STATE_MENU      177
#define IDB_INSERT_STATE                177
#define IDR_CMDE_INSERT_ITEM_MENU       177
#define IDD_CMDE_CMD_DLG                178
#define IDB_INSERT_STATE_DIS            178
#define IDD_CE_EXE_CMD_DLG              178
#define IDD_SAVE_CONFIGURATION_DLG      179
#define IDD_APP_GENERAL_SETTINGS_DLG    180
#define IDI_MVT_FILE_ICON               180
#define IDD_COMMAND_EXE_PANE            181
#define IDB_BITMAP1                     183
#define IDB_BITMAP2                     194
#define IDB_BITMAP3                     195
#define IDB_PI_DEVICE_BMP               195
#define IDB_BITMAP4                     196
#define IDB_BITMAP5                     197
#define IDR_TOOLBAR1                    199
#define IDR_IOCARD_RESET_TOOLBAR        201
#define IDB_TITLE_BMP                   206
#define IDB_CE_CMD_BMP                  207
#define IDB_CE_CMD_STATE_BMP            208
#define IDB_REMOVE_BMP                  209
#define IDB_BITMAP6                     210
#define IDB_COPY_BMP                    210
#define IDD_CE_TOGGLE_COM_DLG           211
#define IDD_CE_BOARD_RESET_DLG          212
#define IDC_IO_CARD_CTRL_DLG            212
#define IDC_IO_CARD_DLG                 212
#define IDD_CE_CLEAR_WIN_DLG            213
#define IDB_PATTERN_BMP                 215
#define IDB_CE_CMD_STATE_BMP1           216
#define IDB_PATTERN_ENTRY_BMP           216
#define IDD_HARDWARE_MODULES_PANE       217
#define IDB_HW_MODULE_BMP               217
#define IDB_HW_MODULE_CTRL_BMP          217
#define IDB_MV_DEVICE_BMP               218
#define IDD_ODPG_CTRL_READWRITE_REG_DLG 218
#define IDD_UNKNOWN_I2C_DEV_CTRL_DLG    221
#define IDB_CE_EXE                      222
#define IDD_CE_UNKNOWN_I2C_DEV_RW_DLG   222
#define IDD_ODPG_SELECT_PATTERN_BIT_DLG 227
#define IDD_CE_CMD_SEQ_DLG              228
#define IDB_BITMAP7                     229
#define IDB_MENU_COPY_BITMAP            229
#define IDB_MENU_PASTE_BITMAP           230
#define IDB_MENU_DUPLICATE_BITMAP       231
#define IDD_SUB20_ADC_CTRL_DLG          233
#define IDB_HW_MODULE_BMP2              233
#define IDB_HW_MODULE_MUX_CHAN_BMP1     234
#define IDD_SUMMIT_SMM205_DLG           235
#define IDB_HW_MODULE_CTRL_UNIT_BMP2    235
#define IDB_OPEN_FILE                   238
#define IDB_PROPERTIES_BMP              239
#define IDB_BITMAP8                     240
#define IDB_REFRESH_HW_MODDULE_TREE     240
#define IDB_RESET_HW_MODDULE_TREE       241
#define IDB_BITMAP10                    243
#define IDB_SAVE_FILE                   244
#define IDD_HW_MODULE_PROPERTIES_DLG    245
#define IDB_HW_MODULE_ADC_VOL_BMP       246
#define IDB_HW_MODULE_ADC_CUR_BMP       247
#define IDD_SUB20_GPIO_UNIT_DLG         248
#define IDD_SUB20_HW_MODULE_CTRL_ADC_UNIT_CUR_VOL_ITEM_MODLS_DLG 249
#define IDD_CLOCK_ETP_DLG               250
#define IDD_SUMMIT_SMM205_SETTINGS_DLG  251
#define IDB_IO_INPUT                    253
#define IDB_IO_OUTPUT                   254
#define IDB_IO_UNKNOWN                  255
#define IDB_IO_ERROR                    256
#define IDD_MVT_UPDATE_DLG              257
#define IDD_MARVELL_DEVICE_HWMODULE_DLG 258
#define IDD_APP_POWER_CTRL_SETTINGS_DLG 259
#define IDI_HW_MODULE_CTRL_UNIT_ICON    260
#define IDR_POWER_CTRL_TOOLBAR          261
#define IDD_HW_MODULE_CTRL_UNIT_SET_I2C_FREQ_DLG 264
#define IDD_PLATFORM_INFO_PANE          265
#define IDD_TEMPERATURE_MONITOR_DLG     267
#define IDB_PI_SMALL_BOARD_BMP          269
#define IDB_PI_BOARD_BMP                271
#define IDB_PI_INFO_BMP                 273
#define IDB_PI_SUBUNIT_BMP              274
#define IDB_BITMAP9                     275
#define IDB_PI_MODULE_BMP               275
#define IDB_PI_HWMODULE_BMP             275
#define IDD_PLATFORM_INFO_UPDATE_DIALOG 276
#define IDB_PI_SWMODULE_BMP             277
#define IDD_MARVELL_DEVICE_PM_HWMODULE_DLG 277
#define IDB_PI_UNIT_DIS_BMP             278
#define IDD_MARVELL_DEVICE_SYSTEM_PROFILER_HWMODULE_DLG 278
#define IDB_PI_UNIT_EN_BMP              279
#define IDD_SYS_PROFILER_LOG_DLG        280
#define IDI_GRAPH_ICON                  285
#define IDB_GRAPH_ICON                  286
#define IDB_GRAPH_ICON_SEL              287
#define IDC_VERSION_STR                 1000
#define IDC_COM_PORT_COMBO              1001
#define IDC_BAUD_RATE_COMBO             1002
#define IDC_WND_NAME_COMBO              1003
#define IDC_LIST1                       1004
#define IDC_TFTP_FILE_LIST              1004
#define IDC_LIST_CTRL                   1004
#define IDC_CMDE_STATES_LIST_BOX        1004
#define IDC_SUB20_GPIO_UNIT_LIST_CTRL   1004
#define IDC_ADD_TFTP_FILE_BTN           1005
#define IDC_REMOVE_TFTP_FILE_BTN        1006
#define IDC_LOAD_IO_FILE_BTN            1006
#define IDC_LOAD_TFTP_FILE_BTN          1007
#define IDC_REMOVE_IO_BTN2              1007
#define IDC_TFTP_LOAD_ADDRESS           1008
#define IDC_PROGRAM_ARGS                1009
#define IDC_LOAD_N_GO                   1010
#define IDC_BURN_TO_FS                  1011
#define IDC_AS_IS                       1012
#define IDC_EXECUTABLE                  1013
#define IDC_TFTP_CONNECTION_STATUS      1014
#define IDC_TFTP_CONNECT_BTN            1015
#define IDC_PROGRESS1                   1016
#define IDC_TFTP_LOAD_PROGRESS          1016
#define IDC_NEW_SCRIPT_BTN              1017
#define IDC_REMOVE_ALL_TFTP_FILE_BTN2   1017
#define IDC_CMDE_INSERT_STATE_BTN       1018
#define IDC_AUTO_DETECT_LOAD_ADDR       1018
#define IDC_REMOVE_SCRIPT_BTN           1019
#define IDC_CMDE_ADD_STATE_BTN1         1019
#define IDC_LOAD_SCRIPT_BTN             1020
#define IDC_SCRIPT_LIST                 1021
#define IDC_SCRIPT_VIEW                 1022
#define IDC_SCRIPT_NAME_EDIT            1023
#define IDC_LINE_DELAY_EDIT             1024
#define IDC_BROWSE_BTN                  1025
#define IDC_CMDE_REMOVE_ALL_CMD_BTN     1025
#define IDC_CMDE_REMOVE_STATE_          1026
#define IDC_CHECK1                      1027
#define IDC_SAVE_SCRIPT_LIST_CHECK      1027
#define IDC_PROMPT_TO_SAVE_SCRIPTS_CHECK 1027
#define IDC_ANALYZE_ON_SELECTION_CHECK  1027
#define IDC_CON_AUTO_CHECK              1027
#define IDC_EN_MESSAGING_CHECK          1027
#define IDC_IO0_CHECK                   1027
#define IDC_CE_EXE_ALL_CHECK            1027
#define IDC_CE_CHECK_RES_FAIL_IF_FOUND_CHECK 1027
#define IDC_CMDE_EXE_ALL_CHECK          1027
#define IDC_CMDE_CMD_STOP_ON_ERR_CHECK  1027
#define IDC_SC_SAVE_SCRIPTS_CHECK       1027
#define IDC_PROMPT_TO_SAVE_SESSION_CHECK 1027
#define IDC_CE_INFINITE_LOOP_CHECK      1027
#define IDC_HW_MODULES_DET_HW_MODULES_ON_STARTUP_CHECK 1027
#define IDC_GEN_I2C_DEV_CTRL_SEND_STOP_CHECK 1027
#define IDC_ENABLE_SEQ_EXE_CHECK        1027
#define IDC_CE_COM_TOGGLE_DIS_CHECK     1027
#define IDC_HW_MODULE_PANE_DET_ON_STARTUP 1027
#define IDC_HW_MODULE_ADC_MOD_DLG_SHOW_GRID_CHECK 1027
#define IDC_REM_DUP_STRINGS_MENU_CHECK  1027
#define IDC_RELOAD_LAST_EVENTS_CHECK    1027
#define IDC_FORCE_CACHEABLE_LOAD_ADDR   1027
#define IDC_CMDE_CMD_LOG_OUTPUT_CHECK   1028
#define IDC_CMDE_REMOVE_ALL_STATES_BTN  1028
#define IDC_TFTP_FAIL_CHECK             1028
#define IDC_PROMPT_TO_SAVE_ENTIRE_SETTINGS_CHECK 1028
#define IDC_VIEW_TAB                    1029
#define IDC_CMDE_CMD_PROMPT_ON_ERR_CHECK2 1029
#define IDC_PROMPT_TO_SAVE_SESSION_CHECK2 1029
#define IDC_CHECK_FOR_NEW_UPDATES       1029
#define IDC_LOAD_COMMAND_EDIT           1030
#define IDC_ENABLE_IPM_MSG_ON_STARTUP   1030
#define IDC_BURN_AS_IS_COMMAND_EDIT     1031
#define IDC_BURN_EXE_COMMAND_EDIT       1032
#define IDC_RUN_COMMAND_EDIT            1033
#define IDC_LOAD_ADDRESS                1034
#define IDC_APP_SETTINGS_TAB            1035
#define IDC_LOAD_DEFAULT_SCRIPTS_CHECK  1036
#define IDC_DEFAULT_SCRIPTS_PATH_EDIT   1037
#define IDC_BUTTON1                     1039
#define IDC_SHIFT_RIGHT_BTN             1039
#define IDC_CLEAR_HISTORY_BTN           1039
#define IDC_MAIL_SETTINGS               1039
#define IDC_CE_EXE_BTN                  1039
#define IDC_CE_CHECK_RESULT_BROWSE_BTN  1039
#define IDC_CMDE_EXE_BTN                1039
#define IDC_CMDE_CMD_LOG_FILE_BROWSE_BTN 1039
#define IDC_CANCEL_BTN                  1039
#define IDC_CE_EXECUTE_BTN              1039
#define IDC_ODPG_CTRL_RW_REG_BTN        1039
#define IDC_GPIO_UNIT_UPDATE_SELECTED_BTN 1039
#define IDC_TFTP_FILE_GO_BTN            1039
#define IDC_HW_MODULE_ADC_MOD_DLG_XL_SNAPSHOT_BTN 1039
#define IDC_SAVE_AS_DEFAULT_BTN         1039
#define IDC_RESTORE_PLATFORM_INFO_DEFAULTS_BTN 1039
#define IDC_SYS_PROFILER_LOAD_EVENTS_BTN 1039
#define IDC_RESTORE_DEFAULTS_BTN        1040
#define IDC_EDIT3                       1042
#define IDC_BIT0                        1042
#define IDC_MAIL_MSG                    1042
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_AVRG_EDIT 1042
#define IDC_EDIT35                      1043
#define IDC_DATA_EDIT                   1043
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_MIN_EDIT 1043
#define IDC_EDIT4                       1044
#define IDC_BIT1                        1044
#define IDC_GEN_I2C_DEV_CTRL_HEX_EDIT   1044
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_MAX_EDIT 1044
#define IDC_EDIT5                       1045
#define IDC_BIT2                        1045
#define IDC_GEN_I2C_DEV_CTRL_READ_BC_EDIT 1045
#define IDC_EDIT6                       1046
#define IDC_BIT3                        1046
#define IDC_EDIT7                       1047
#define IDC_BIT4                        1047
#define IDC_EDIT8                       1048
#define IDC_BIT5                        1048
#define IDC_EDIT9                       1049
#define IDC_BIT6                        1049
#define IDC_EDIT10                      1050
#define IDC_BIT7                        1050
#define IDC_CMD_MAX_LEN_EDIT            1050
#define IDC_EDIT11                      1051
#define IDC_BIT8                        1051
#define IDC_EDIT12                      1052
#define IDC_BIT9                        1052
#define IDC_EDIT13                      1053
#define IDC_BIT10                       1053
#define IDC_EDIT14                      1054
#define IDC_BIT11                       1054
#define IDC_EDIT15                      1055
#define IDC_BIT12                       1055
#define IDC_EDIT16                      1056
#define IDC_BIT13                       1056
#define IDC_EDIT17                      1057
#define IDC_BIT14                       1057
#define IDC_EDIT18                      1058
#define IDC_BIT15                       1058
#define IDC_EDIT19                      1059
#define IDC_BIT16                       1059
#define IDC_EDIT20                      1060
#define IDC_BIT17                       1060
#define IDC_EDIT21                      1061
#define IDC_BIT18                       1061
#define IDC_EDIT22                      1062
#define IDC_BIT19                       1062
#define IDC_EDIT23                      1063
#define IDC_BIT20                       1063
#define IDC_EDIT24                      1064
#define IDC_BIT21                       1064
#define IDC_EDIT25                      1065
#define IDC_BIT22                       1065
#define IDC_EDIT26                      1066
#define IDC_BIT23                       1066
#define IDC_EDIT27                      1067
#define IDC_BIT24                       1067
#define IDC_EDIT28                      1068
#define IDC_BIT25                       1068
#define IDC_EDIT29                      1069
#define IDC_BIT26                       1069
#define IDC_EDIT30                      1070
#define IDC_BIT27                       1070
#define IDC_EDIT31                      1071
#define IDC_BIT28                       1071
#define IDC_EDIT32                      1072
#define IDC_BIT29                       1072
#define IDC_EDIT33                      1073
#define IDC_BIT30                       1073
#define IDC_EDIT34                      1074
#define IDC_BIT31                       1074
#define IDC_RADIO1                      1075
#define IDC_DEC_RADIO                   1075
#define IDC_SEND_KEY_CODES_AS_IS        1075
#define IDC_CE_TOGGLE_IO_ON_RADIO       1075
#define IDC_CE_COMPARE_STR_RADIO        1075
#define IDC_CE_TOGGLEIO_ON_RADIO        1075
#define IDC_GEN_I2C_DEV_CTRL_READ_RADIO 1075
#define IDC_ODPG_CTRL_READ_RADIO        1075
#define IDC_IO_CARD_CTRL_ON_RADIO       1075
#define IDC_SUMMIT_CHANNEL_B_RADIO      1075
#define IDC_RADIO2                      1076
#define IDC_HEX_RADIO                   1076
#define IDC_ACT_AS_HISTORY              1076
#define IDC_CE_TOGGLE_IO_OFF_RADIO      1076
#define IDC_COMPARE_TEXT_FILE_RADIO     1076
#define IDC_CE_TOGGLEIO_OFF_RADIO       1076
#define IDC_ODPG_CTRL_BUS_RADIO         1076
#define IDC_GEN_I2C_DEV_CTRL_WRITE_RADIO 1076
#define IDC_IO_CARD_CTRL_OFF_RADIO      1076
#define IDC_SUMMIT_CHANNEL_A_RADIO      1076
#define IDC_EDIT1                       1077
#define IDC_SHIFT_VAL_EDIT              1077
#define IDC_SHIFT_EDIT                  1077
#define IDC_CMD_FILTER_EDIT             1077
#define IDC_MAIL_RECIPIENT              1077
#define IDC_SENDER                      1077
#define IDC_CE_TOGGLE_IO_NUM_EDIT       1077
#define IDC_CE_CHECK_RES_EDIT           1077
#define IDC_CE_WAIT_FOR_STR_TIMEOUT_EDIT 1077
#define IDC_CMDE_CMD_LOOPCOUNT_EDIT     1077
#define IDC_PULSE_WIDTH                 1077
#define IDC_IOCARD_PULSE_WIDTH_EDIT     1077
#define IDC_CE_STATUS_WINDOW_EDIT       1077
#define IDC_CE_TOGGLEIO_EDIT            1077
#define IDC_IO_CARD_CTRL_TOGGLEIO_EDIT  1077
#define IDC_HW_MODULE_PROP_DIS_NAME     1077
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_NAME_EDIT 1077
#define IDC_HW_MODULE_CTRL_UNIT_I2C_SET_FREQ_EDIT 1077
#define IDC_BUTTON2                     1078
#define IDC_SHIFT_LEFT_BTN              1078
#define IDC_RESTORE_DEFAULT_BTN         1078
#define IDC_MAIL_SUBJECT                1078
#define IDC_CE_I2C_TOGGLE_IO_ADDR_EDIT  1078
#define IDC_CE_SET_DELAY_RAND_LOW_EDIT  1078
#define IDC_CMD_LEN_THRS_EDIT           1078
#define IDC_CE_CMD_SEQ_CLEAR_ALL_BTN    1078
#define IDC_CE_MORE_OPTIONS_BTN         1078
#define IDC_HW_MODULE_PROP_NAME         1078
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_RESISTOR_EDIT 1078
#define IDC_GPIO_UNIT_RESTORE_DEFAULTS_BTN 1078
#define IDC_CMD_MIN_LEN_THRS_EDIT       1078
#define IDC_CLEAR_BTN                   1079
#define IDC_MAILSERVER                  1079
#define IDC_CE_SET_DELAY_RAND_HIGH_EDIT 1079
#define IDC_SC_BROWSE_BTN               1079
#define IDC_CE_CMD_SEQ_RESET_BTN        1079
#define IDC_HW_MODULE_PROP_IF_NAME      1079
#define IDC_CMD_MAX_LEN_THRS_EDIT       1079
#define IDC_SWAP_BTN                    1080
#define IDC_HW_MODULE_PROP_ID           1080
#define IDC_NOT_BTN                     1081
#define IDC_CE_TOGGLEIO_DELAY_EDIT      1081
#define IDC_IO_CARD_CTRL_DELAY_EDIT     1081
#define IDC_MSB_LSB_STATIC              1082
#define IDC_CE_TOGGLEIO_EDIT2           1082
#define IDC_IO_CARD_CTRL_TOGGLEIO_EDIT2 1082
#define IDC_CE_TOGGLEIO_ON_RADIO2       1083
#define IDC_IO_CARD_CTRL_ON_RADIO2      1083
#define IDC_THEME_LIST                  1084
#define IDC_CE_TOGGLEIO_OFF_RADIO2      1084
#define IDC_IO_CARD_CTRL_OFF_RADIO2     1084
#define IDC_DATA_BITS_COMBO             1085
#define IDC_PARITY_COMBO                1086
#define IDC_COMBO3                      1087
#define IDC_STOP_BITS_COMBO             1087
#define IDC_MB_VALUE                    1088
#define IDP_MARVELL_LOGO                1089
#define IDC_SEND_MAIL_CHECK             1090
#define IDC_MAIL_DURATION_COMBO         1093
#define IDC_MODE                        1094
#define IDC_SEND_MAIL                   1095
#define IDC_HIDE_MSG_CHECK              1097
#define IDC_APPEND_NEWLINE_CHECK        1098
#define IDC_IO1_CHECK                   1099
#define IDC_ADD_IO_BTN                  1104
#define IDC_LIST2                       1105
#define IDC_IP_ADDRESS_LIST             1105
#define IDC_CMDE_CMD_LIST_CTRL          1105
#define IDC_ADD_CMD_BTN                 1106
#define IDC_LOAD_CMD_BTN                1107
#define IDC_CMD_LIST_CTRL               1108
#define IDC_REMOVE_CMD_BTN              1109
#define IDC_REMOVE_ALL_CMD_BTN          1110
#define IDC_IOCARD_I2C_ADDR_EDIT        1117
#define IDC_HW_MODULES_I2C_ADDR_EDIT    1117
#define IDC_IOCARD_RESET_IO_EDIT        1118
#define IDC_CE_EXE_ALL_LOOPCOUNT_EDIT   1118
#define IDC_HW_MODULES_RESET_IO_EDIT    1118
#define IDC_IOCARD_POWERUP_IO_EDIT      1119
#define IDC_CE_CHECK_RESULT_TEXT        1122
#define IDC_CE_EXECUTE_CMD_EDIT         1123
#define IDC_CE_SET_DELAY_FIXED_RADIO    1124
#define IDC_CE_SET_DELAY_RAND_RADIO     1125
#define IDC_CE_SET_DELAY_FIXED_EDIT     1126
#define IDC_CE_WAIT_FOR_STR_EDIT        1129
#define IDC_CMDE_ADD_CMD_BTN            1132
#define IDC_CMDE_REMOVE_CMD_BTN         1133
#define IDC_CMDE_FILE_BTN               1134
#define IDC_CMDE_LOOPCOUNT_EDIT         1138
#define IDC_CMDE_SPIN_CTRL              1139
#define IDC_CMDE_CMD_COMPORT_COMBO      1140
#define IDC_CMDE_CMD_LOOPCOUNT_SPIN     1142
#define IDC_CMDE_CMD_LOG_FILE_PATH_EDIT 1143
#define IDC_CMDE_OK_BTN                 1144
#define IDC_CMDE_CANCEL_BTN             1145
#define IDC_CMDE_CMD_NAME_EDIT          1146
#define IDC_CHECK2                      1148
#define IDC_IO_NORMALLY_OPEN            1148
#define IDC_SC_SAVE_TFTP_FILES_CHECK    1148
#define IDC_CE_CMD_EN_CHECK             1148
#define IDC_CE_COM_TOGGLE_CON_CHECK     1148
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_AVRG_CHECK 1148
#define IDC_CMDE_INFINITE_EXE_CHECK     1149
#define IDC_LOOPINDEX_TEXT              1150
#define IDC_CHANGE_COLOR_BTN            1152
#define IDC_LOAD_SESSION_PROPERTIES_BTN 1153
#define IDC_SC_CURR_WIN_SESSION_CHECK   1154
#define IDC_SC_SAVE_COMMAND_EXE_FILES_CHECK 1155
#define IDC_SC_CONFIG_FILE_PATH_COMBO   1157
#define IDC_SC_SAVE_HWMODUELS_SETTINGS_CHECK 1158
#define IDC_SAVE_BTN                    1159
#define IDC_CE_REFRESH_EXP_LIST_BTN     1161
#define IDC_CE_CMD_TREE_CTRL            1162
#define IDC_CE_NEW_CMD_BTN              1163
#define IDC_CE_REMOVE_CMD_BTN           1164
#define IDC_CMD_LIST_FRAME_STATIC       1165
#define IDC_CE_REMOVE_ALL_CMD_BTN       1166
#define IDC_CE_FILE_CMD_BTN             1167
#define IDC_CE_REFRESH_EXP_LIST_BTN2    1168
#define IDC_CE_HW_MODULE_TREE_CTRL      1169
#define IDC_HW_MODULE_TREE_CTRL         1169
#define IDC_CMD_LIST_FRAME_STATIC2      1170
#define IDC_CE_ADD_EXP_LIST_BTN         1171
#define IDC_CE_CMD_TREE                 1175
#define IDC_SRC_TREE                    1176
#define IDC_CE_CMD_TREE2                1176
#define IDC_DST_TREE                    1177
#define IDC_CMD_EXE_CMD_SETTING_TREE    1177
#define IDC_TARGET_WIN_COMBO            1179
#define IDC_HW_MODULE_PANE_REFRESH_TREE_BTN 1204
#define IDC_HW_MODULE_CTRL_COMBO        1205
#define IDC_ODPG_CTRL_TARGET_DEVICE_COMBO 1210
#define IDC_ODPG_CTRL_PATTERN_TREE      1211
#define IDC_ODPG_CTRL_READ_COMP_DATA_CHECK 1213
#define IDC_ODPG_CTRL_DATA_BUS_RADIO    1215
#define IDC_ODPG_CTRL_DATA_BUS_ADDR_EDIT 1216
#define IDC_ODPG_CTRL_BUS_WIDTH_COMBO   1217
#define IDC_ODPG_CTRL_STOP_COND_CONT_RADIO 1218
#define IDC_ODPG_CTRL_STOP_COND_SINGLE_PATTERN_RADIO 1219
#define IDC_ODPG_CTRL_STOP_COND_PRE_DEF_ADDR_RADIO 1220
#define IDC_ODPG_CTRL_STOP_COND_ERR_DATA_RADIO 1221
#define IDC_ODPG_CTRL_STOP_COND_PRE_DEF_PHASE_COUNT_RADIO 1222
#define IDC_ODPG_CTRL_STOP_COND_PRE_DEF_PHASE_COUNT_EDIT 1223
#define IDC_ODPG_CTRL_REG_RW_OFFSET_EDIT 1228
#define IDC_ODPG_CTRL_REG_RW_VALUE_EDIT 1229
#define IDC_ODPG_CTRL_REG_READ_RADIO    1230
#define IDC_ODPG_CTRL_REG_WRITE_RADIO   1231
#define IDC_ODPG_CTRL_EXE_BTN           1232
#define IDC_CE_GENERIC_I2C_DEV_RW_READ_RADIO 1235
#define IDC_CE_GENERIC_I2C_DEV_RW_WRITE_RADIO 1236
#define IDC_CE_GENERIC_I2C_DEV_RW_SEND_STOP_CHECK 1237
#define IDC_CE_GENERIC_I2C_DEV_RW_BC_EDIT 1238
#define IDC_CE_GENERIC_I2C_DEV_RW_HEX_EDIT 1239
#define IDC_CE_LOOP_COUNT_EDIT          1240
#define IDC_CE_LOOP_COUNT_STATIC        1242
#define IDC_ODPG_PATTERN_BIT_COMBO      1244
#define IDC_ODPG_CTRL_WRITE_RADIO       1245
#define IDC_CE_CMD_SEQ_DST_TREE         1246
#define IDC_CE_CMD_SEQ_SRC_TREE         1247
#define IDC_SEL_BIT_STATIC              1249
#define IDC_CE_COM_TOGGLE_DELAY_EDIT    1250
#define IDC_IO_CARD_CTRL_EN_PULSE_MODE_CHECK 1252
#define IDC_SUMMIT_SMM205_CTRL_WRITE_RADIO 1253
#define IDC_SUMMIT_SMM205_CTRL_READ_RADIO 1254
#define IDC_SUMMIT_SMM205_CTRL_VOL_EDIT 1255
#define IDC_SUMMIT_SMM205_SETTINGS_MIN_EDIT 1256
#define IDC_SUMMIT_SMM205_SETTINGS_MAX_EDIT 1257
#define IDC_ID_STATIC                   1258
#define IDC_SUMMIT_SMM205_SETTINGS_EXT_REF_EDIT 1258
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_MIN_RANGE_EDIT 1261
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_MAX_RANGE_EDIT 1262
#define IDC_HW_MODULE_ADC_MOD_DLG_RESET_BTN 1263
#define IDC_HW_MODULE_ADC_MOD_DLG_GRAPH_STATIC 1264
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_SAMPLE_RATE_SLIDER 1266
#define IDC_HW_MODULE_ADC_MOD_DLG_PAUSE_BTN 1267
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_SAMPLE_RATE_STATIC 1268
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_SAMPLE_INTERVAL_SLIDER 1269
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_GRID_SIZE_SLIDER 1270
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_STAT_SAMPLE_INT_STATIC 1271
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_GRID_SIZE_STATIC 1272
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_RESISTOR_VAL_STATIC 1273
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_CUR_RANGE_STATIC 1274
#define IDC_HW_MODULE_ADC_MOD_DLG_VOL_CUR_STATS_STATIC 1275
#define IDC_CLOCK_ETP_CTRL_FREQ_EDIT    1276
#define IDC_CLOCK_ETP_CTRL_REF_EDIT     1277
#define IDC_SUMMIT_DLG_SETTINGS_BTN     1277
#define IDC_CLOCK_ETP_CTRL_RANGE_EDIT   1278
#define IDC_SUMMIT_SMM205_SETTINGS_NAME_EDIT 1279
#define IDC_SUMMIT_MIN_MAX_STATIC       1280
#define IDC_GPIO_UNIT_UPDATE_ALL_BTN    1281
#define IDC_MVT_UPDATE_HISTORY_EDIT     1282
#define IDC_MVT_UPDATE_STATIC           1283
#define IDC_MARVELL_DEVICE_HWMODULE_OFFSET_EDIT 1285
#define IDC_MARVELL_DEVICE_HWMODULE_VALUE_EDIT 1286
#define IDC_MARVELL_DEVICE_HWMODULE_READ_RADIO 1287
#define IDC_MARVELL_DEVICE_HWMODULE_WRITE_RADIO 1288
#define IDC_POWER_CTRL_TOGGLE_POWER_IO_STATE_COMBO 1290
#define IDC_BOARD_RESET_HWMODULE_TREE   1292
#define IDC_POWER_CTRL_RESET_IO_STATE_COMBO 1293
#define IDC_BOARD_POWER_HWMODULE_TREE   1295
#define IDC_POWER_CTRL_TOGGLE_POWER_IO_NUMBER_COMBO 1296
#define IDC_POWER_CTRL_RESET_IO_NUMBER_COMBO 1297
#define IDC_POWER_CTRL_TOGGLE_POWER_IO_NUMBER_STATIC 1298
#define IDC_POWER_CTRL_TOGGLE_POWER_IO_STATE_STATIC 1299
#define IDC_POWER_CTRL_TOGGLE_POWER_IO_STATE_STATIC2 1300
#define IDC_SUB20_HWMODULE_ADC_CUR_VOL_AMP_SLIDER 1305
#define IDC_SUB20_HWMODULE_ADC_CUR_VOL_OFFSET_SLIDER 1306
#define IDC_HW_MODULE_CTRL_CUR_VOL_AMP_SLIDER_STATIC 1307
#define IDC_HW_MODULE_CTRL_CUR_VOL_OFFSET_SLIDER_STATIC 1308
#define IDC_PLATFORM_INFO_BIN_FILES_FRAME_STATIC 1310
#define IDC_PLATFORM_INFO_TREE_FRAME_STATIC 1311
#define IDC_PLATFORM_INFO_TREE          1312
#define IDD_PLATFORMINFOSETTINGSTREE    1315
#define IDC_GRID_PLACEHOLDER            1316
#define IDC_TEMP_MONITOR_GRAPH_STATIC   1317
#define IDC_TEMP_LABEL_STATIC           1318
#define IDC_NEW_FILES_STATIC            1319
#define IDC_MAX_AMP_STATIC              1320
#define IDC_MAX_OFFSET_STATIC           1321
#define IDC_MARVELL_DEVICE_PM_GRAPH     1322
#define IDC_MARVELL_DEVICE_SP_GRAPH2    1323
#define IDC_MARVELL_DEVICE_SP_GRAPH3    1324
#define IDC_MARVELL_DEVICE_SP_GRAPH4    1325
#define IDC_MARVELL_DEVICE_SP_TREE1     1326
#define IDC_MARVELL_DEVICE_SP_TREE4     1327
#define IDC_MARVELL_DEVICE_SP_TREE3     1328
#define IDC_MARVELL_DEVICE_SP_TREE2     1329
#define IDC_MARVELL_DEVICE_SP_GRAPH1    1330
#define IDC_EVENT_GRAPH1_STATIC         1332
#define IDC_EVENT_GRAPH2_STATIC         1333
#define IDC_RICHEDIT21                  1333
#define IDC_EVENT_GRAPH3_STATIC         1334
#define IDC_EVENT_GRAPH4_STATIC         1335
#define IDC_SYS_PROFILER_OPTION_BUTTON  1336
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_NEW_FONT                     32773
#define ID_PORT_DISCONNECT              32775
#define ID_PORT_PROPERTIES              32778
#define ID_VIEW_CLEARBUFFER             32782
#define ID_PORT_CONNECT                 32783
#define ID_VIEW_CAPTURETOFILE           32784
#define ID_BUTTON32785                  32785
#define ID_VIEW_WIN_CONTENT             32786
#define ID_SETTINGS                     32787
#define ID_APP_SETTINGS                 32788
#define ID_BUTTON32791                  32791
#define ID_VIEW_WRAPTEXT                32792
#define ID_FILE_EXPORTSCRIPTS           32793
#define ID_FILE_IMPORTSCRIPTS           32794
#define ID_FILE_SENDTEXTFILE            32796
#define ID_HISTORY_ASAF                 32813
#define ID_HISTORY_HISTORY              32814
#define ID_HISTORY_                     32815
#define ID_HISTORY_COMMANDHISTORY       32816
#define ID_CMD_2                        32820
#define ID_CMD_3                        32822
#define ID_CMD_4                        32824
#define ID_HISTORY_COMMANDHISTORY32825  32825
#define ID_HISTORY_ASAF32826            32826
#define ID_LOAD_TFTP_FILE               32829
#define ID__SEND                        32839
#define ID__COPY                        32840
#define ID__PASTE                       32841
#define ID_IOCARD_BOARD_RESET           32847
#define ID_IOCARD_RESET_TOOLBAR         32847
#define ID_FILE_EXPORTCOMMANDLIST       32849
#define ID_FILE_IMPORTCOMMANDLIST       32850
#define ID__CLEARWINDOW                 32851
#define ID__SETDELAY                    32852
#define ID__EXECUTECOMMAND              32853
#define ID__CHECKRESULT                 32854
#define ID__WAITFORSTRING               32855
#define ID__TOGGLEIO                    32856
#define ID__SAVEALLCOMMANDTOFILE        32857
#define ID__LOADCOMMANDSFROMFILE        32858
#define ID_INSERTBEFORE_EXECUTECOMMAND  32861
#define ID_INSERTBEFORE_CHECKRESULT     32862
#define ID_INSERTBEFORE_WAITFORSTRING   32863
#define ID_INSERTBEFORE_TOGGLEIO        32864
#define ID_INSERTAFTER_TOGGLEIO         32865
#define ID_INSERTBEFORE_CLEARWINDOW     32866
#define ID_INSERTAFTER_CLEARWINDOW      32867
#define ID_INSERTAFTER_SETDELAY         32868
#define ID_INSERTAFTER_EXECUTECOMMAND   32869
#define ID_INSERTAFTER_CHECKRESULT      32870
#define ID_INSERTAFTER_WAITFORSTRING    32871
#define ID_INSERTBEFORE_SETDELAY        32872
#define ID_SAVECOMMANDS_SELECTEDCOMMANDS 32873
#define ID_SAVECOMMANDS_ALLCOMMANDS     32874
#define ID_LOADCOMMANDS_ALLCOMMANDS     32876
#define ID_LOADCOMMANDS_INDIVIDUALCOMMAND 32877
#define ID_CMD_EXECUTER_EXE             32880
#define ID_FILE_                        32882
#define ID_FILE_SAVECONFIGURATION       32883
#define ID_FILE_LOADCONFIGURATION       32884
#define ID_FILE_RESTORELASTCONFIGURATION 32887
#define ID_HELP_CHECKFORUPDATES         32889
#define ID__NEWCOMMAND                  32891
#define ID_INSERTBEFORE_NEWCOMMAND      32892
#define ID_INSERTAFTER_NEWCOMMAND       32893
#define ID__REMOVECOMMAND               32894
#define ID_INSERTBEFORE_REMOVECOMMAND   32895
#define ID_INSERTAFTER_REMOVECOMMAND    32896
#define ID__REMOVE                      32897
#define ID_DETECT_HW_MODULES            32901
#define ID_Menu                         32902
#define ID                              32903
#define ID_BUTTON32904                  32904
#define ID__TOGGLEIO32905               32905
#define ID_IOCARD_TOGGLEIO              32906
#define ID__VOLTAGECONTROLLER           32907
#define ID_VOLTAGECONTROLLER_SETVOLTAGE 32908
#define ID_POWER_CTRL_POWER             32910
#define ID_POWER_CTRL_RESET             32911
#define ID_INDICATOR_LOGO               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        289
#define _APS_NEXT_COMMAND_VALUE         32913
#define _APS_NEXT_CONTROL_VALUE         1337
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
