// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "sportax1.h"

/////////////////////////////////////////////////////////////////////////////
// CSportax1

IMPLEMENT_DYNCREATE(CSportax1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSportax1 properties

/////////////////////////////////////////////////////////////////////////////
// CSportax1 operations
